version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./.env:/app/.env:ro
      # Temporary volume for audio processing
      - audio_temp:/app/audios
    restart: unless-stopped
    environment:
      - TZ=UTC  # Set your timezone here
    deploy:
      resources:
        limits:
          memory: 10G  # Adjust based on your needs, especially for the Whisper model

volumes:
  audio_temp:
    driver: local